"""Supervisor — background decision layer for proactive AI behavior.

Runs every 5 minutes and decides:
1. Whether a ritual (morning/midday/eod) should run
2. Whether it's a late/recovery execution
3. Whether to proactively ping the user if they're idle
4. Whether to check in on an active work session at mid-point / end

All ping/follow-up messages are generated by Claude with full context —
no templates. Supervisor only decides WHEN to ping, Claude decides WHAT to say.
"""

import logging
import uuid
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo

import anthropic
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.database import direct_session_factory
from app.dependencies import DAVIT_USER_ID
from app.models.daily_context import DailyContext
from app.models.daily_plan import DailyPlan
from app.models.daily_state import DailyState
from app.models.task import UnifiedTask
from app.services.ai.adaptive_messenger import build_message
from app.services.ai.daily_planner import DailyPlanner

logger = logging.getLogger(__name__)

USER_TZ = ZoneInfo("Asia/Yerevan")

# Ritual schedule: trigger time + recovery_until_hour (after which we give up)
RITUAL_SCHEDULE = [
    {"type": "morning", "hour": 10, "minute": 30, "recovery_until_hour": 14},
    {"type": "midday",  "hour": 14, "minute":  0, "recovery_until_hour": 18},
    {"type": "eod",     "hour": 21, "minute":  0, "recovery_until_hour": 23},
]

ON_TIME_WINDOW_MINUTES = 30

# Proactive ping settings
PING_INTERVAL_MINUTES = 15
WORK_CHECK_NO_ESTIMATE_MINUTES = 5
WORKING_HOURS_START = 10
# No fixed end — Nini stops pinging only when user says goodnight
# (sleep mode tracked via DailyContext.work_session = {"type": "sleep"})

_planner = DailyPlanner()


class Supervisor:
    """Evaluates and executes daily rituals with full context awareness."""

    async def run_cycle(self) -> None:
        """Main supervisor cycle — called every 5 minutes."""
        async with direct_session_factory() as db:
            try:
                now = datetime.now(USER_TZ)
                state = await self._get_or_create_state(db)
                context = await self._get_or_create_context(db)

                # Late night (00:00–09:59): today's context is empty because
                # it's a new calendar day, but the user may still be working
                # from yesterday. Use yesterday's context for ping decisions.
                if now.hour < WORKING_HOURS_START and not context.user_active_today:
                    yesterday_ctx = await self._get_yesterday_context(db)
                    if yesterday_ctx and yesterday_ctx.user_active_today:
                        context = yesterday_ctx

                await self._check_all_rituals(db, state, context, now)
                await self._check_proactive_ping(db, state, context, now)
            except Exception:
                logger.exception("Supervisor cycle failed")

    # ------------------------------------------------------------------
    # Core ritual logic
    # ------------------------------------------------------------------

    async def _check_all_rituals(
        self, db: AsyncSession, state: DailyState, context: DailyContext, now: datetime
    ) -> None:
        for ritual in RITUAL_SCHEDULE:
            await self._check_ritual(db, state, context, ritual, now)

    async def _check_ritual(
        self,
        db: AsyncSession,
        state: DailyState,
        context: DailyContext,
        ritual: dict,
        now: datetime,
    ) -> None:
        plan_type = ritual["type"]
        status = getattr(state, f"{plan_type}_status")

        if status in ("done", "skipped"):
            return

        trigger_dt = now.replace(
            hour=ritual["hour"], minute=ritual["minute"],
            second=0, microsecond=0,
        )
        recovery_until_dt = now.replace(
            hour=ritual["recovery_until_hour"], minute=0,
            second=0, microsecond=0,
        )

        if now < trigger_dt:
            return

        if now >= recovery_until_dt:
            setattr(state, f"{plan_type}_status", "skipped")
            await db.commit()
            logger.info("Ritual '%s' skipped — past recovery window (%s)", plan_type, now.strftime("%H:%M"))
            return

        on_time_window_end = trigger_dt + timedelta(minutes=ON_TIME_WINDOW_MINUTES)
        is_recovery = now > on_time_window_end

        await self._execute_ritual(db, state, context, plan_type, is_recovery, now)

    async def _execute_ritual(
        self,
        db: AsyncSession,
        state: DailyState,
        context: DailyContext,
        plan_type: str,
        is_recovery: bool,
        now: datetime,
    ) -> None:
        """Generate plan, build adaptive message, send to user, update state."""
        try:
            plan = await self._generate_plan(db, plan_type)

            reminder_count = getattr(state, f"{plan_type}_reminder_count", 0)
            message = build_message(plan, context, is_recovery, reminder_count)

            sent = await _send_to_user(message)
            if not sent:
                logger.warning("Ritual '%s' message not delivered — will retry next cycle", plan_type)
                return

            setattr(state, f"{plan_type}_status", "done")
            setattr(state, f"{plan_type}_executed_at", now.astimezone(timezone.utc))
            await db.commit()

            from app.services.ai.adaptive_messenger import decide_tone
            tone = decide_tone(context, plan, reminder_count, is_recovery)
            await self._record_interaction(
                db, context,
                interaction_type="ritual",
                category=plan_type,
                summary=message[:200],
                tone=tone,
            )

            logger.info("Ritual '%s' executed (is_recovery=%s, tone=%s)", plan_type, is_recovery, tone)

        except Exception:
            logger.exception("Failed to execute ritual '%s'", plan_type)

    # ------------------------------------------------------------------
    # Proactive ping logic
    # ------------------------------------------------------------------

    async def _check_proactive_ping(
        self,
        db: AsyncSession,
        state: DailyState,
        context: DailyContext,
        now: datetime,
    ) -> None:
        """Ping user if idle, or check in on active work session."""

        # Check if user said goodnight (sleep mode)
        work_session = context.work_session
        if work_session and work_session.get("type") == "sleep":
            return

        # Before working hours: only ping if user was active yesterday
        # (late night work continuation). context is already set to
        # yesterday's context by run_cycle() in this case.
        if now.hour < WORKING_HOURS_START:
            if not context.user_active_today:
                return  # No activity yesterday either — don't ping at night

        # During working hours: wait for morning ritual or first user message
        if now.hour >= WORKING_HOURS_START:
            if state.morning_status not in ("done",) and not context.user_active_today:
                return

        # EOD is just a report, NOT end of work. Keep pinging after EOD.

        if work_session:
            await self._check_work_session(db, context, state, work_session, now)
        else:
            await self._check_idle_ping(db, context, now)

    async def _check_work_session(
        self,
        db: AsyncSession,
        context: DailyContext,
        state: DailyState,
        session: dict,
        now: datetime,
    ) -> None:
        """Check mid-point and end of an active work session."""
        try:
            started_at_str = session.get("started_at", "")
            if not started_at_str:
                return

            started_at = datetime.fromisoformat(started_at_str)
            if started_at.tzinfo is None:
                started_at = started_at.replace(tzinfo=timezone.utc)

            now_utc = now.astimezone(timezone.utc)
            elapsed_min = (now_utc - started_at).total_seconds() / 60
            task_title = session.get("task_title", "задача")
            estimate_min = session.get("estimate_min")
            last_ping = context.last_ping_at

            should_ping = False
            ping_reason = ""

            if estimate_min:
                # Divide estimate into 3 intervals: check at 1/3, 2/3, and end
                interval_min = estimate_min / 3
                checks_done = session.get("checks_done", 0)
                next_check_at = interval_min * (checks_done + 1)

                if elapsed_min >= estimate_min and checks_done >= 3:
                    # Time is up AND all checks done, still no response → idle ping
                    await self._check_idle_ping(db, context, now)
                    return
                elif elapsed_min >= next_check_at:
                    should_ping = True
                    remaining = max(0, int(estimate_min - elapsed_min))
                    if elapsed_min >= estimate_min:
                        ping_reason = "work_session_time_up"
                    else:
                        ping_reason = "work_session_progress_check"
                    session["checks_done"] = checks_done + 1
            else:
                # No estimate — check every 5 min until user provides estimate
                last_check_str = session.get("last_check_at")
                if last_check_str:
                    last_check = datetime.fromisoformat(last_check_str)
                    if last_check.tzinfo is None:
                        last_check = last_check.replace(tzinfo=timezone.utc)
                    if (now_utc - last_check).total_seconds() < WORK_CHECK_NO_ESTIMATE_MINUTES * 60:
                        return
                should_ping = True
                ping_reason = "work_session_no_estimate_check"
                session["last_check_at"] = now_utc.isoformat()

            if should_ping:
                # Global anti-spam guard: if we pinged recently, skip this cycle.
                # Prevents duplicate check-ins when supervisor ticks every 5 min
                # or when multiple app instances overlap briefly.
                min_gap_min = (estimate_min / 3) if estimate_min else WORK_CHECK_NO_ESTIMATE_MINUTES
                if last_ping:
                    lp = last_ping if last_ping.tzinfo else last_ping.replace(tzinfo=timezone.utc)
                    since_last_ping_sec = (now_utc - lp).total_seconds()
                    if since_last_ping_sec < min_gap_min * 60:
                        return

                msg = await self._generate_proactive_message(
                    db, context, ping_reason,
                    ping_count=context.ping_count or 0,
                    work_session=session,
                    elapsed_min=int(elapsed_min),
                )
                sent = await _send_to_user(msg)
                if sent:
                    context.work_session = dict(session)
                    context.last_ping_at = now_utc
                    context.ping_count = (context.ping_count or 0) + 1
                    await db.commit()
                    logger.info("Work session ping sent: reason=%s, task='%s'", ping_reason, task_title)
                else:
                    logger.warning("Work session ping NOT delivered — will retry next cycle")

        except Exception:
            logger.exception("Error in _check_work_session")

    async def _check_idle_ping(
        self,
        db: AsyncSession,
        context: DailyContext,
        now: datetime,
    ) -> None:
        """Ping if user has been idle for 15+ minutes."""
        try:
            now_utc = now.astimezone(timezone.utc)
            last_active = context.user_last_active_at
            last_ping = context.last_ping_at
            ping_count = context.ping_count or 0

            inactive_sec = 0
            if last_active:
                la = last_active if last_active.tzinfo else last_active.replace(tzinfo=timezone.utc)
                inactive_sec = (now_utc - la).total_seconds()
                if inactive_sec < PING_INTERVAL_MINUTES * 60:
                    return
            else:
                inactive_sec = PING_INTERVAL_MINUTES * 60 + 1

            # Respect ping interval
            if last_ping:
                lp = last_ping if last_ping.tzinfo else last_ping.replace(tzinfo=timezone.utc)
                since_last_ping = (now_utc - lp).total_seconds()
                if since_last_ping < PING_INTERVAL_MINUTES * 60:
                    return

            msg = await self._generate_proactive_message(
                db, context, "idle_ping",
                ping_count=ping_count + 1,
                inactive_min=int(inactive_sec / 60),
            )
            sent = await _send_to_user(msg)

            if sent:
                context.last_ping_at = now_utc
                context.ping_count = ping_count + 1
                await db.commit()
                logger.info("Idle ping #%d sent (inactive %d min)", ping_count + 1, int(inactive_sec / 60))
            else:
                logger.warning("Idle ping #%d NOT delivered — DB not updated, will retry next cycle", ping_count + 1)

        except Exception:
            logger.exception("Error in _check_idle_ping")

    # ------------------------------------------------------------------
    # Context-aware message generation via Claude
    # ------------------------------------------------------------------

    async def _generate_proactive_message(
        self,
        db: AsyncSession,
        context: DailyContext,
        reason: str,
        ping_count: int = 0,
        inactive_min: int = 0,
        work_session: dict | None = None,
        elapsed_min: int = 0,
    ) -> str:
        """Generate a contextual follow-up message using Claude."""

        # Gather context for Claude
        last_interactions = (context.interactions or [])[-10:]
        interaction_summary = "\n".join(
            f"  [{i.get('timestamp', '?')[:16]}] {i.get('type', '?')}: {i.get('summary', '')}"
            for i in last_interactions
        ) or "  (нет взаимодействий сегодня)"

        # Get overdue and urgent tasks
        task_context = await self._get_task_context(db)

        # Work session info
        ws_info = ""
        if work_session:
            ws_info = (
                f"\nАктивная рабочая сессия:\n"
                f"  Задача: {work_session.get('task_title', '?')}\n"
                f"  Оценка: {work_session.get('estimate_min', 'не указана')} мин\n"
                f"  Прошло: {elapsed_min} мин\n"
                f"  Mid-check: {'сделан' if work_session.get('mid_checked') else 'нет'}\n"
                f"  Результат спрошен: {'да' if work_session.get('result_asked') else 'нет'}"
            )

        # Tone escalation guide
        if ping_count <= 1:
            tone_guide = "Мягко но настойчиво. Покажи что следишь."
        elif ping_count <= 3:
            tone_guide = "Настойчиво. Ты пишешь не первый раз и ждёшь ответа."
        elif ping_count <= 5:
            tone_guide = "Жёстко. Это уже пинг #{count}. Давишь серьёзно.".format(count=ping_count)
        else:
            tone_guide = "Максимальное давление. Пинг #{count}. Не отстанешь.".format(count=ping_count)

        # Build remaining time info for work sessions
        remaining_info = ""
        if work_session and isinstance(work_session, dict) and work_session.get("estimate_min"):
            remaining = max(0, work_session["estimate_min"] - elapsed_min)
            remaining_info = f" Осталось ~{int(remaining)} мин из {work_session['estimate_min']}."

        ws = work_session or {}
        reason_descriptions = {
            "idle_ping": f"Давит молчит уже {inactive_min} минут. Нужно выяснить чем он занимается и подтолкнуть к работе.",
            "work_session_progress_check": f"Давит работает над задачей. Прошло {elapsed_min} мин.{remaining_info} Спроси как прогресс, успевает ли.",
            "work_session_time_up": f"Время на задачу ВЫШЛО (прошло {elapsed_min} мин из {ws.get('estimate_min', '?')}). Спроси результат — закрыл или нет.",
            "work_session_no_estimate_check": f"Давит работает над задачей но не дал оценку по времени. Прошло {elapsed_min} мин. Узнай как дела и попроси оценку.",
        }

        now_str = datetime.now(USER_TZ).strftime("%H:%M")

        prompt = f"""Ты — Нини, проджект-менеджер Давита. 26 лет, дерзкая, требовательная, используешь сленг.
Ты НЕ ассистент, ты PM который требует результат.

Сейчас: {now_str} (Ереван)
Причина сообщения: {reason_descriptions.get(reason, reason)}
Тон: {tone_guide}
Это пинг номер: {ping_count}

Последние взаимодействия за сегодня:
{interaction_summary}
{ws_info}

Задачи:
{task_context}

Напиши ОДНО короткое follow-up сообщение (1-3 предложения).
Учитывай контекст последних сообщений — если Давит говорил что чем-то занимается, спроси конкретно про это.
Не повторяй предыдущие сообщения. Пиши как в мессенджере, на русском."""

        try:
            client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key or None)
            response = await client.messages.create(
                model="claude-haiku-4-5-20251001",
                max_tokens=200,
                messages=[{"role": "user", "content": prompt}],
            )
            msg = response.content[0].text.strip()
            logger.info("Generated proactive message: %s", msg[:80])
            return msg
        except Exception:
            logger.exception("Failed to generate proactive message via Claude")
            # Fallback: minimal context-aware message
            if work_session:
                return f"Как там «{work_session.get('task_title', 'задача')}»?"
            return f"Молчишь уже {inactive_min} мин. Что делаешь?"

    async def _get_task_context(self, db: AsyncSession) -> str:
        """Get a compact summary of overdue and urgent tasks."""
        now = datetime.now(timezone.utc)
        base = [
            UnifiedTask.user_id == DAVIT_USER_ID,
            UnifiedTask.archived.is_(False),
        ]

        # Overdue
        overdue_result = await db.execute(
            select(UnifiedTask).where(
                *base,
                UnifiedTask.due_date < now,
                UnifiedTask.status_type.notin_(["done", "closed"]),
            ).order_by(UnifiedTask.due_date.asc()).limit(5)
        )
        overdue = overdue_result.scalars().all()

        # Due today (Yerevan time boundaries converted to UTC)
        yerevan_today = datetime.now(USER_TZ).date()
        today_start = datetime(yerevan_today.year, yerevan_today.month, yerevan_today.day, tzinfo=USER_TZ).astimezone(timezone.utc)
        today_end = today_start + timedelta(days=1)
        due_today_result = await db.execute(
            select(UnifiedTask).where(
                *base,
                UnifiedTask.due_date >= today_start,
                UnifiedTask.due_date < today_end,
                UnifiedTask.status_type.notin_(["done", "closed"]),
            ).limit(5)
        )
        due_today = due_today_result.scalars().all()

        lines = []
        if overdue:
            lines.append(f"Просроченные ({len(overdue)}):")
            for t in overdue:
                lines.append(f"  - {t.title} (дедлайн: {t.due_date.strftime('%d.%m') if t.due_date else '?'})")
        if due_today:
            lines.append(f"На сегодня ({len(due_today)}):")
            for t in due_today:
                lines.append(f"  - {t.title}")
        if not overdue and not due_today:
            lines.append("Нет просроченных или срочных задач на сегодня.")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Plan generation
    # ------------------------------------------------------------------

    async def _generate_plan(self, db: AsyncSession, plan_type: str) -> DailyPlan:
        if plan_type == "morning":
            return await _planner.generate_morning_plan(db)
        elif plan_type == "midday":
            return await _planner.generate_midday_replan(db)
        else:
            return await _planner.generate_eod_review(db)

    # ------------------------------------------------------------------
    # State management
    # ------------------------------------------------------------------

    async def _get_or_create_state(self, db: AsyncSession) -> DailyState:
        today = datetime.now(USER_TZ).date()
        result = await db.execute(
            select(DailyState).where(
                DailyState.user_id == DAVIT_USER_ID,
                DailyState.state_date == today,
            )
        )
        state = result.scalar_one_or_none()
        if not state:
            state = DailyState(
                id=uuid.uuid4(),
                user_id=DAVIT_USER_ID,
                state_date=today,
            )
            db.add(state)
            await db.commit()
            await db.refresh(state)
        return state

    async def _get_or_create_context(self, db: AsyncSession) -> DailyContext:
        today = datetime.now(USER_TZ).date()
        result = await db.execute(
            select(DailyContext).where(
                DailyContext.user_id == DAVIT_USER_ID,
                DailyContext.context_date == today,
            )
        )
        ctx = result.scalar_one_or_none()
        if not ctx:
            ctx = DailyContext(
                id=uuid.uuid4(),
                user_id=DAVIT_USER_ID,
                context_date=today,
            )
            db.add(ctx)
            await db.commit()
            await db.refresh(ctx)
        return ctx

    async def _get_yesterday_context(self, db: AsyncSession) -> DailyContext | None:
        """Get yesterday's context — used for late-night continuity."""
        from datetime import date as date_type
        yesterday = datetime.now(USER_TZ).date() - timedelta(days=1)
        result = await db.execute(
            select(DailyContext).where(
                DailyContext.user_id == DAVIT_USER_ID,
                DailyContext.context_date == yesterday,
            )
        )
        return result.scalar_one_or_none()

    # ------------------------------------------------------------------
    # Context updates
    # ------------------------------------------------------------------

    async def _record_interaction(
        self,
        db: AsyncSession,
        context: DailyContext,
        interaction_type: str,
        category: str,
        summary: str,
        tone: str,
    ) -> None:
        interactions = list(context.interactions or [])
        interactions.append({
            "type": interaction_type,
            "category": category,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "summary": summary,
            "tone": tone,
        })
        context.interactions = interactions[-50:]
        context.interaction_count = (context.interaction_count or 0) + 1
        await db.commit()


# ------------------------------------------------------------------
# Activity tracking (called from bot.py)
# ------------------------------------------------------------------

async def record_user_activity(message_text: str, category: str = "user_message") -> None:
    """Update DailyContext with a user interaction. Called from bot.py on every message.
    Also resets ping_count — user responded, so escalation counter starts over.
    """
    try:
        async with direct_session_factory() as db:
            now_utc = datetime.now(timezone.utc)
            today = datetime.now(USER_TZ).date()

            result = await db.execute(
                select(DailyContext).where(
                    DailyContext.user_id == DAVIT_USER_ID,
                    DailyContext.context_date == today,
                )
            )
            ctx = result.scalar_one_or_none()
            if not ctx:
                ctx = DailyContext(
                    id=uuid.uuid4(),
                    user_id=DAVIT_USER_ID,
                    context_date=today,
                )
                db.add(ctx)

            ctx.user_last_active_at = now_utc
            ctx.user_active_today = True
            ctx.interaction_count = (ctx.interaction_count or 0) + 1
            ctx.ping_count = 0

            interactions = list(ctx.interactions or [])
            interactions.append({
                "type": "user_message",
                "category": category,
                "timestamp": now_utc.isoformat(),
                "summary": message_text[:100],
                "tone": None,
            })
            ctx.interactions = interactions[-50:]

            await db.commit()
    except Exception:
        logger.exception("Failed to record user activity in DailyContext")


# ------------------------------------------------------------------
# Telegram helper
# ------------------------------------------------------------------

async def _send_to_user(text: str) -> bool:
    """Send message to user via Telegram. Returns True if sent successfully."""
    if not text:
        return False
    try:
        import asyncio
        import app.services.telegram.bot as bot_module

        # Wait up to 30s for bot to initialize (race condition after deploy)
        for _ in range(6):
            if bot_module._bot is not None:
                break
            logger.info("Waiting for Telegram bot to initialize...")
            await asyncio.sleep(5)

        if bot_module._bot is None:
            logger.warning("Telegram bot still not initialized after 30s — message dropped")
            return False

        await bot_module.send_proactive_message(text)
        return True
    except Exception:
        logger.exception("Failed to send proactive Telegram message")
        return False


# Singleton instance
supervisor = Supervisor()
