"""initial schema - all tables

Revision ID: 69d753fb93ad
Revises: 
Create Date: 2026-04-06 12:58:54.232061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69d753fb93ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('clickup_user_id', sa.BigInteger(), nullable=True),
    sa.Column('clickup_token', sa.Text(), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clickup_user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('clickup_team_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('clickup_api_token', sa.Text(), nullable=True),
    sa.Column('webhook_id', sa.String(), nullable=True),
    sa.Column('webhook_secret', sa.Text(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_full_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'clickup_team_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('clickup_id', sa.String(), nullable=False),
    sa.Column('clickup_type', sa.Enum('space', 'folder', 'list', name='clickup_entity_type'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company_tag', sa.String(), nullable=True),
    sa.Column('priority_tier', sa.SmallInteger(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clickup_id')
    )
    op.create_index('idx_projects_company', 'projects', ['user_id', 'company_tag'], unique=False)
    op.create_table('unified_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('clickup_task_id', sa.String(), nullable=True),
    sa.Column('clickup_custom_id', sa.String(), nullable=True),
    sa.Column('clickup_list_id', sa.String(), nullable=True),
    sa.Column('clickup_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_type', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('clickup', 'manual', 'telegram', name='task_source'), server_default='clickup', nullable=False),
    sa.Column('clickup_priority', sa.SmallInteger(), nullable=True),
    sa.Column('nini_priority', sa.Enum('critical', 'high', 'medium', 'low', 'none', name='nini_priority'), server_default='none', nullable=False),
    sa.Column('priority_reason', sa.Text(), nullable=True),
    sa.Column('company_tag', sa.String(), nullable=True),
    sa.Column('task_type_tag', sa.String(), nullable=True),
    sa.Column('assignees', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_closed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_done', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('time_estimate', sa.BigInteger(), nullable=True),
    sa.Column('time_spent', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('points', sa.REAL(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sync_hash', sa.String(), nullable=True),
    sa.Column('sync_direction', sa.String(), server_default='inbound', nullable=False),
    sa.Column('sync_conflict', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clickup_task_id')
    )
    op.create_index('idx_tasks_clickup', 'unified_tasks', ['clickup_task_id'], unique=False)
    op.create_index('idx_tasks_due', 'unified_tasks', ['user_id', 'due_date'], unique=False, postgresql_where='due_date IS NOT NULL')
    op.create_index('idx_tasks_updated', 'unified_tasks', ['user_id', 'date_updated'], unique=False)
    op.create_index('idx_tasks_user_company', 'unified_tasks', ['user_id', 'company_tag'], unique=False)
    op.create_index('idx_tasks_user_priority', 'unified_tasks', ['user_id', 'nini_priority'], unique=False)
    op.create_index('idx_tasks_user_status', 'unified_tasks', ['user_id', 'status'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['unified_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_user', 'knowledge_base', ['user_id', 'content_type'], unique=False)
    op.create_table('sync_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('inbound', 'outbound', 'full_sync', name='sync_direction_enum'), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('clickup_task_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', 'skipped', 'conflict', name='sync_status_enum'), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['unified_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_log_idempotency', 'sync_log', ['payload_hash'], unique=False)
    op.create_index('idx_sync_log_user_time', 'sync_log', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sync_log_user_time', table_name='sync_log')
    op.drop_index('idx_sync_log_idempotency', table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_index('idx_kb_user', table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index('idx_tasks_user_status', table_name='unified_tasks')
    op.drop_index('idx_tasks_user_priority', table_name='unified_tasks')
    op.drop_index('idx_tasks_user_company', table_name='unified_tasks')
    op.drop_index('idx_tasks_updated', table_name='unified_tasks')
    op.drop_index('idx_tasks_due', table_name='unified_tasks', postgresql_where='due_date IS NOT NULL')
    op.drop_index('idx_tasks_clickup', table_name='unified_tasks')
    op.drop_table('unified_tasks')
    op.drop_index('idx_projects_company', table_name='projects')
    op.drop_table('projects')
    op.drop_table('workspaces')
    op.drop_table('users')
    # ### end Alembic commands ###
