"""add_workspace_space_list_names_to_tasks

Revision ID: 714780a6cd43
Revises: d4a848414799
Create Date: 2026-04-06 22:16:33.708619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714780a6cd43'
down_revision: Union[str, None] = 'd4a848414799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unified_tasks', sa.Column('workspace_name', sa.String(), nullable=True))
    op.add_column('unified_tasks', sa.Column('space_name', sa.String(), nullable=True))
    op.add_column('unified_tasks', sa.Column('list_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unified_tasks', 'list_name')
    op.drop_column('unified_tasks', 'space_name')
    op.drop_column('unified_tasks', 'workspace_name')
    # ### end Alembic commands ###
